export const countriesWeWork = [
  // { name: "Bangladesh", code: "bd" },
  // { name: "Burundi", code: "bi" },
  // { name: "Canada", code: "ca" },
  // { name: "Ghana", code: "gh" },
  {
    name: "India",
    code: "in",
    states: [
      { name: "Eastern Uttar Pradesh", lat: 26.85, lng: 80.949997, code: "in" },
      { name: "Jaipur", lat: 26.9124, lng: 75.7873, code: "in" },
      { name: "Delhi", lat: 28.6139, lng: 77.209, code: "in" },
      { name: "Indore", lat: 22.7196, lng: 75.8577, code: "in" },
      { name: "Chhattisgarh", lat: 21.2787, lng: 81.8661, code: "in" },
      { name: "Koderma", lat: 24.467, lng: 85.5937, code: "in" },
      { name: "Asansol", lat: 23.6739, lng: 86.9524, code: "in" },
    ],
  },
  // { name: "Jordan", code: "jo" },
  // { name: "Lebanon", code: "lb" },
  // { name: "Mali", code: "ml" },
  // { name: "Mozambique", code: "mz" },
  // { name: "Pakistan", code: "pk" },
  // { name: "Palestine", code: "ps" },
  // { name: "Rwanda", code: "rw" },
  // { name: "South Sudan", code: "ss" },
  // { name: "Tanzania", code: "tz" },
  // { name: "Thailand", code: "th" },
  // { name: "Uganda", code: "ug" },
  // { name: "United Kingdom", code: "gb" },
];
