export const countriesWeWork = [
  { name: "Bangladesh", code: "bd" },
  { name: "Burundi", code: "bi" },
  { name: "Canada", code: "ca" },
  { name: "Ghana", code: "gh" },
  { name: "India", code: "in" },
  { name: "Jordan", code: "jo" },
  { name: "Lebanon", code: "lb" },
  { name: "Mali", code: "ml" },
  { name: "Mozambique", code: "mz" },
  { name: "Pakistan", code: "pk" },
  { name: "Palestine", code: "ps" },
  { name: "Rwanda", code: "rw" },
  { name: "South Sudan", code: "ss" },
  { name: "Tanzania", code: "tz" },
  { name: "Thailand", code: "th" },
  { name: "Uganda", code: "ug" },
  { name: "United Kingdom", code: "gb" },
];
